apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmchartmonday-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmchartmonday2
  template:
    metadata:
      labels:
        app: helmchartmonday2
    spec:
      containers:
      - name: helmchartmonday2
        image: helmchartmondaycontainer.azurecr.io/bhanu9505508737/helmchartmonday2:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: bhanu258737